server:
  port: 8090


springdoc:
  swagger-ui:
    path: /swagger-ui.html



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cablogdb?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update