server:
  port: 8090


mongo:
  isAuthenticated: false
  host: localhost
  port: 27017
  database: cablog


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cablogdb?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update